# -*- coding: utf-8 -*-
"""CodigoCostos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ffyS33bQwOXhbYc6t2-eyCzUqBel1ggq

# Rendimiento y Costos I/O: Árboles B vs B+
"""

import math

def calcular_costos_io(n_registros, tamaño_pagina_bytes, tamaño_clave_bytes, tamaño_dato_bytes):

    # Tamaño de un puntero (típicamente 8 bytes en sistemas 64-bit)
    puntero_bytes = 8

    # Árbol B
    espacio_por_entrada_b = puntero_bytes + tamaño_clave_bytes + tamaño_dato_bytes
    fan_out_b = tamaño_pagina_bytes // espacio_por_entrada_b
    altura_b = math.log(n_registros, max(2, fan_out_b))

    # Árbol B+
    espacio_por_entrada_b_plus = puntero_bytes + tamaño_clave_bytes
    fan_out_b_plus = tamaño_pagina_bytes // espacio_por_entrada_b_plus
    altura_b_plus = math.log(n_registros, max(2, fan_out_b_plus))

    print(f"RESULTADOS PARA {n_registros:,} REGISTROS")
    print("-" * 40)
    print(f"B-Tree   | Fan-out: {fan_out_b:3d} | Altura (I/O): {math.ceil(altura_b)}")
    print(f"B+ Tree  | Fan-out: {fan_out_b_plus:3d} | Altura (I/O): {math.ceil(altura_b_plus)}")
    print("-" * 40)
    print(f"Conclusión: El B+ Tree requiere {math.ceil(altura_b) - math.ceil(altura_b_plus)} menos accesos a disco por búsqueda.")

# Parámetros de prueba
calcular_costos_io(
    n_registros=1_000_000,
    tamaño_pagina_bytes=4096, # 4KB
    tamaño_clave_bytes=16,
    tamaño_dato_bytes=128
)

class NodoHojaBPlus:
    def __init__(self, datos, siguiente=None):
        self.datos = datos
        self.siguiente = siguiente

hoja3 = NodoHojaBPlus([20, 25, 30])
hoja2 = NodoHojaBPlus([10, 12, 15], siguiente=hoja3)
hoja1 = NodoHojaBPlus([1, 5, 8], siguiente=hoja2)

def buscar_rango(nodo_inicio, minimo, maximo):
    print(f"Buscando rango [{minimo}-{maximo}] sin volver a la raíz...")
    actual = nodo_inicio
    resultado = []
    while actual:
        for d in actual.datos:
            if minimo <= d <= maximo:
                resultado.append(d)
        actual = actual.siguiente
    return resultado

print(f"Valores encontrados: {buscar_rango(hoja1, 5, 22)}")