# -*- coding: utf-8 -*-
"""Nearest Neighbor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RFY--YvKJm98EqO_IFAQ_JUXOTMc8nO1

function nearest(node, target, best):
    if node is null:
        return best

    update best if node is closer

    choose branch (left or right)

    best = nearest(next_branch, target, best)

    if splitting plane is close enough:
        best = nearest(other_branch, target, best)

    return best
"""

import math

class Node:
    def __init__(self, point, axis, left=None, right=None):
        self.point = point      # (x, y)
        self.axis = axis        # 0 = x, 1 = y
        self.left = left
        self.right = right


def distance(p1, p2):
    return math.sqrt((p1[0] - p2[0])**2 + (p1[1] - p2[1])**2)


def nearest_neighbor(node, target, best=None):
    if node is None:
        return best

    # Inicializar mejor
    if best is None:
        best = node.point

    # Comparar distancia actual
    if distance(target, node.point) < distance(target, best):
        best = node.point

    # Elegir rama (descenso)
    axis = node.axis
    if target[axis] < node.point[axis]:
        next_branch = node.left
        other_branch = node.right
    else:
        next_branch = node.right
        other_branch = node.left

    # Bajar por el árbol
    best = nearest_neighbor(next_branch, target, best)

    # PODA (pruning)
    if abs(target[axis] - node.point[axis]) < distance(target, best):
        best = nearest_neighbor(other_branch, target, best)

    return best

# Árbol manual simple
tree = Node((7,2), 0,
    left=Node((5,4), 1,
        left=Node((2,3), 0),
        right=Node((4,7), 0)
    ),
    right=Node((9,6), 1)
)

target = (6,5)

result = nearest_neighbor(tree, target)
print("Vecino más cercano:", result)